name: "Build frontend"

on:
  push:
    branches: [ main ]
    paths:
      - "frontend/**"
      - "!frontend/**.md"

defaults:
  run:
    working-directory: "./frontend"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Run linter"
        run: make lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Run unit tests"
        run: make test

  publish:
    runs-on: ubuntu-latest
    needs: [lint, test]
    env:
      # used by build & push Makefile targets
      IMAGE_VERSION: ${{ github.sha }}
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Build container image"
        run: make

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: "Push image to GitHub Container Registry"
        run:
          make push
