name: "Build frontend"

on:
  workflow_call:
    secrets:
      registry_url:
        required: true
      registry_username:
        required: true
      registry_password:
        required: true

defaults:
  run:
    working-directory: "./frontend"

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Run linter"
        run: make lint

  test:
    name: "Unit test"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Run unit tests"
        run: make test

  build:
    name: "Build"
    runs-on: ubuntu-latest
    needs: [lint, test]
    env:
      # used by build & push Makefile targets
      IMAGE_VERSION: ${{ github.sha }}
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.registry_url }}
          username: ${{ secrets.registry_username }}
          password: ${{ secrets.registry_password }}

      - name: "Build container image"
        run: make

      - name: "Push image to GitHub Container Registry"
        run: make push

  e2e:
    name: "End-to-end test"
    runs-on: ubuntu-latest
    needs: [build]
    container:
      image: cypress/included:9.1.0
      volumes:
        - ${{ format('{0}:/e2e', github.workspace) }}
    steps:
      - run: ls -lah
      - run: ls -lah /e2e
      - name: "Execute tests"
        run: cypress run --project /e2e
