name: "Build frontend"

on:
  workflow_call:
    secrets:
      registry_url:
        required: true
      registry_username:
        required: true
      registry_password:
        required: true
      google_maps_key:
        required: true

jobs:
  test-environment:
    name: "Build test environment"
    runs-on: ubuntu-latest
    env:
      # used by build & push Makefile targets
      IMAGE_VERSION: ${{ github.sha }}
    defaults:
      run:
        working-directory: "./frontend"
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.registry_url }}
          username: ${{ secrets.registry_username }}
          password: ${{ secrets.registry_password }}

      - name: "Build container image"
        run: make build-test-environment

      - name: "Push image to GitHub Container Registry"
        run: make push-test-environment

  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    needs: [ test-environment ]
    container:
      image: ${{ format('ghcr.io/covik/vfm-frontend-testing:{0}', github.sha) }}
      credentials:
        username: ${{ secrets.registry_username }}
        password: ${{ secrets.registry_password }}
    steps:
      - name: "Execute linter"
        working-directory: "/testing"
        run: |
          HOME=/home/node yarn lint --no-fix

  unit-test:
    name: "Unit test"
    runs-on: ubuntu-latest
    needs: [test-environment]
    container:
      image: ${{ format('ghcr.io/covik/vfm-frontend-testing:{0}', github.sha) }}
      credentials:
        username: ${{ secrets.registry_username }}
        password: ${{ secrets.registry_password }}
    steps:
      - name: "Execute tests"
        working-directory: "/testing"
        run: |
          HOME=/home/node yarn test:unit:ci --colors

  component-test:
    name: "Component test"
    runs-on: ubuntu-latest
    needs: [test-environment]
    container:
      image: ${{ format('ghcr.io/covik/vfm-frontend-testing:{0}', github.sha) }}
      credentials:
        username: ${{ secrets.registry_username }}
        password: ${{ secrets.registry_password }}
    strategy:
      matrix:
        browser: ["chrome", "firefox", "edge"]
    steps:
      - name: "Execute tests"
        working-directory: "/testing"
        run: | 
          HOME=/home/node cypress run --component \
            --browser ${{ matrix.browser }}

  build:
    name: "Build"
    runs-on: ubuntu-latest
    needs: [lint, unit-test, component-test]
    env:
      # used by build & push Makefile targets
      IMAGE_VERSION: ${{ github.sha }}
    defaults:
      run:
        working-directory: "./frontend"
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.registry_url }}
          username: ${{ secrets.registry_username }}
          password: ${{ secrets.registry_password }}

      - name: "Build container image"
        env:
          GOOGLE_MAPS_KEY: ${{ secrets.google_maps_key }}
        run: make

      - name: "Push image to GitHub Container Registry"
        run: make push

  e2e:
    name: "End-to-end test"
    runs-on: ubuntu-latest
    needs: [build, test-environment]
    container:
      image: ${{ format('ghcr.io/covik/vfm-frontend-testing:{0}', github.sha) }}
      credentials:
        username: ${{ secrets.registry_username }}
        password: ${{ secrets.registry_password }}
    services:
      frontend:
        image: ${{ format('ghcr.io/covik/vfm-frontend:{0}', github.sha) }}
        credentials:
          username: ${{ secrets.registry_username }}
          password: ${{ secrets.registry_password }}
        ports:
          - 80:80
    steps:
      - name: "Execute tests"
        working-directory: "/testing"
        run: |
          HOME=/home/node cypress run --e2e \
            --browser chrome \
            --config baseUrl=http://frontend
