name: "Build frontend"

on:
  workflow_call:
    secrets:
      registry_url:
        required: true
      registry_username:
        required: true
      registry_password:
        required: true

defaults:
  run:
    working-directory: "./frontend"

jobs:
  test-environment:
    name: "Build test environment"
    runs-on: ubuntu-latest
    env:
      # used by build & push Makefile targets
      IMAGE_VERSION: ${{ github.sha }}
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.registry_url }}
          username: ${{ secrets.registry_username }}
          password: ${{ secrets.registry_password }}

      - name: "Build container image"
        run: make build-test-environment

      - name: "Push image to GitHub Container Registry"
        run: make push-test-environment

  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Run linter"
        run: make lint

  test:
    name: "Unit test"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Run unit tests"
        run: make test

  component-test:
    name: "Component test"
    runs-on: ubuntu-latest
    needs: [test-environment]
    container:
      image: ${{ format('ghcr.io/covik/vfm-frontend-testing:{0}', github.sha) }}
      credentials:
        username: ${{ secrets.registry_username }}
        password: ${{ secrets.registry_password }}
    steps:
      - name: "Execute tests"
        run: HOME=/home/node cypress run-ct --browser=chrome
        working-directory: "/testing"

  build:
    name: "Build"
    runs-on: ubuntu-latest
    needs: [lint, test, component-test]
    env:
      # used by build & push Makefile targets
      IMAGE_VERSION: ${{ github.sha }}
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.registry_url }}
          username: ${{ secrets.registry_username }}
          password: ${{ secrets.registry_password }}

      - name: "Build container image"
        run: make

      - name: "Push image to GitHub Container Registry"
        run: make push

  e2e:
    name: "End-to-end test"
    runs-on: ubuntu-latest
    needs: [build]
    container:
      image: cypress/included:9.1.0
    services:
      frontend:
        image: ${{ format('ghcr.io/covik/vfm-frontend:{0}', github.sha) }}
        credentials:
          username: ${{ secrets.registry_username }}
          password: ${{ secrets.registry_password }}
        ports:
          - 80:80
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Install dependencies"
        run: yarn --frozen-lockfile

      - name: "Execute tests"
        run: |
          cypress run --project . \
            --config baseUrl=http://frontend \
            --browser chrome
