name: "Build infrastructure"

on:
  workflow_call:
    secrets:
      registry_url:
        required: true
      registry_username:
        required: true
      registry_password:
        required: true

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./infrastructure"
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.registry_url }}
          username: ${{ secrets.registry_username }}
          password: ${{ secrets.registry_password }}

      - name: "Build image"
        run: make

      - name: "Run unit tests"
        run: make test

      - name: "Push image to GitHub Container Registry"
        run: make push
