name: "Build frontend"

on:
  push:
    branches: [ main ]
    paths:
      - "frontend/**"
      - "!frontend/**.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Lint"
        working-directory: "./frontend"
        run: make lint

      - name: "Unit test"
        working-directory: "./frontend"
        run: make test

      - name: "Build container image"
        working-directory: "./frontend"
        env:
          IMAGE_VERSION: ${{ github.sha }}
        run: make
