name: "Build frontend"

on:
  push:
    branches: [ main ]
    paths:
      - "frontend/**"
      - "!frontend/**.md"

env:
  # used by build & push Makefile targets
  IMAGE_VERSION: ${{ github.sha }}

defaults:
  run:
    working-directory: "./frontend"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Lint"
        run: make lint

      - name: "Unit test"
        run: make test

      - name: "Build container image"
        run: make

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: "Push image to GitHub Container Registry"
        run:
          make push
