name: "Deploy backend/frontend/infrastructure"

on:
  workflow_call:
    inputs:
      type:
        description: "Type of deployment: backend, frontend or infrastructure"
        required: true
        type: string
      image:
        description: "Full infrastructure image tag"
        required: true
        type: string
      application_version:
        required: false
        type: string
    secrets:
      registry_username:
        required: true
      registry_password:
        required: true
      pulumi_token:
        required: true
      digitalocean_token:
        required: false
      cluster_token:
        required: false
      cluster_container_registry_token:
        required: false
      notifications_email_password:
        required: false
      reverse_geocoding_token:
        required: false

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      credentials:
        username: ${{ secrets.registry_username }}
        password: ${{ secrets.registry_password }}
    steps:
      - name: "Deploy"
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.pulumi_token }}
          DIGITALOCEAN_TOKEN: ${{ secrets.digitalocean_token }}
          CLUSTER_TOKEN: ${{ secrets.cluster_token }}
          CLUSTER_CONTAINER_REGISTRY_TOKEN: ${{ secrets.cluster_container_registry_token }}
          APPLICATION_VERSION: ${{ inputs.application_version }}
          NOTIFICATIONS_EMAIL_PASSWORD: ${{ secrets.notifications_email_password }}
          REVERSE_GEOCODING_TOKEN: ${{ secrets.reverse_geocoding_token }}
        run: vfm deploy ${{ inputs.type }}
