name: Deploy infrastructure

on:
  push:
    branches: [ main ]
    paths:
      - "infrastructure/**"
      - "!infrastructure/**.md"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Deploy production infrastructure"
        working-directory: "./infrastructure"
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
          CLUSTER_TOKEN: ${{ secrets.CLUSTER_TOKEN }}
        run: make production
