name: "Build and deploy infrastructure, frontend and backend"

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "**.md"

concurrency: "full-system-deployment"

env:
  IMAGE_VERSION: ${{ github.sha }}
  CONTAINER_REGISTRY_URL: ghcr.io
  CONTAINER_REGISTRY_USERNAME: ${{ github.repository_owner }}
  CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GHCR_TOKEN }}

jobs:
  build-infrastructure:
    name: "Infrastructure"
    uses: Covik/vfm-system/.github/workflows/build-infrastructure.yml@main
    secrets:
      registry_url: ghcr.io
      registry_username: ${{ github.repository_owner }}
      registry_password: ${{ secrets.GHCR_TOKEN }}

  build-frontend:
    name: "Frontend"
    uses: Covik/vfm-system/.github/workflows/build-frontend.yml@main
    secrets:
      registry_url: ghcr.io
      registry_username: ${{ github.repository_owner }}
      registry_password: ${{ secrets.GHCR_TOKEN }}

  deploy-infrastructure:
    name: "Infrastructure"
    uses: Covik/vfm-system/.github/workflows/deploy.yml@main
    needs: [build-infrastructure]
    with:
      type: infrastructure
      image: ${{ format('ghcr.io/covik/vfm-infrastructure:{0}', github.sha) }}
    secrets:
      registry_username: ${{ github.repository_owner }}
      registry_password: ${{ secrets.GHCR_TOKEN }}
      pulumi_token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      digitalocean_token: ${{ secrets.DIGITALOCEAN_TOKEN }}
      cluster_token: ${{ secrets.CLUSTER_TOKEN }}
      cluster_container_registry_token: ${{ secrets.CLUSTER_CONTAINER_REGISTRY_TOKEN }}

  deploy-frontend:
    name: "Frontend"
    uses: Covik/vfm-system/.github/workflows/deploy.yml@main
    needs: [build-infrastructure, build-frontend]
    with:
      type: frontend
      image: ${{ format('ghcr.io/covik/vfm-infrastructure:{0}', github.sha) }}
    secrets:
      registry_username: ${{ github.repository_owner }}
      registry_password: ${{ secrets.GHCR_TOKEN }}
      pulumi_token: ${{ secrets.PULUMI_ACCESS_TOKEN }}

  deploy-backend:
    name: "Backend"
    uses: Covik/vfm-system/.github/workflows/deploy.yml@main
    needs: [build-infrastructure]
    with:
      type: backend
      image: ${{ format('ghcr.io/covik/vfm-infrastructure:{0}', github.sha) }}
    secrets:
      registry_username: ${{ github.repository_owner }}
      registry_password: ${{ secrets.GHCR_TOKEN }}
      pulumi_token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      digitalocean_token: ${{ secrets.DIGITALOCEAN_TOKEN }}
