name: "Build and deploy infrastructure, frontend and backend"

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "**.md"

env:
  IMAGE_VERSION: ${{ github.sha }}
  CONTAINER_REGISTRY_URL: ghcr.io
  CONTAINER_REGISTRY_USERNAME: ${{ github.repository_owner }}
  CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GHCR_TOKEN }}

jobs:
  build-infrastructure:
    name: "Build infrastructure image"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./infrastructure"
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REGISTRY_URL }}
          username: ${{ env.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ env.CONTAINER_REGISTRY_PASSWORD }}

      - name: "Build image"
        working-directory: "./infrastructure"
        run: make

      - name: "Run unit tests"
        working-directory: "./infrastructure"
        run: make test

      - name: "Push image to GitHub Container Registry"
        run:
          make push

  build-frontend:
    name: "Build frontend image"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./frontend"
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REGISTRY_URL }}
          username: ${{ env.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ env.CONTAINER_REGISTRY_PASSWORD }}

      - name: "Build container image"
        run: make

      - name: "Run linter"
        run: make lint

      - name: "Run unit tests"
        run: make test

      - name: "Push image to GitHub Container Registry"
        run:
          make push

  deploy-infrastructure:
    name: "Infrastructure"
    uses: Covik/vfm-system/.github/workflows/deploy.yml@main
    needs: [build-infrastructure]
    with:
      type: infrastructure
      image: ${{ format('ghcr.io/covik/vfm-infrastructure:{0}', github.sha) }}
    secrets:
      registry_username: ${{ github.repository_owner }}
      registry_password: ${{ secrets.GHCR_TOKEN }}
      pulumi_token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      digitalocean_token: ${{ secrets.DIGITALOCEAN_TOKEN }}
      cluster_token: ${{ secrets.CLUSTER_TOKEN }}
      cluster_container_registry_token: ${{ secrets.CLUSTER_CONTAINER_REGISTRY_TOKEN }}

