name: Deploy infrastructure

on:
  push:
    branches: [ main ]
    paths:
      - "infrastructure/**"
      - "!infrastructure/**.md"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Build image"
        working-directory: "./infrastructure"
        run: make

      - name: "Run unit tests"
        working-directory: "./infrastructure"
        run: make test

      - name: "Deploy production infrastructure"
        working-directory: "./infrastructure"
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
          CLUSTER_TOKEN: ${{ secrets.CLUSTER_TOKEN }}
          CLUSTER_CONTAINER_REGISTRY_TOKEN: ${{ secrets.CLUSTER_CONTAINER_REGISTRY_TOKEN }}
        run: make deploy

      - name: "Deploy backend"
        working-directory: "./infrastructure"
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
        run: make deploy-backend

      - name: "Deploy frontend"
        working-directory: "./infrastructure"
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          FRONTEND_VERSION: "useless"
        run: make deploy-frontend
